# Generated by Django 4.2.1 on 2023-05-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_customer_user_alter_invoic_subscription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoic',
            new_name='Invoice',
        ),
    ]
