# Generated by Django 4.2.1 on 2023-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_invoic_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
